  
  
services:

  frontend.td7:
    image : node:22

    volumes:
      - ./:/app
      - /app/node_modules

    working_dir: /app
    ports:
      - "5173:5173"

    command: sh -c "npm install && npm run dev -- --host"