  
  
services:

  frontend.td7:
    image : node:22

    volumes:
      - ./:/app
      - /app/node_modules

    working_dir: /app
    ports:
      - "56789:4173"

    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0"